//! service lib.rs file. Generated by build, if necessary please change in build/templates/service_lib.tera
pub use sea_orm;

pub mod common {
    pub mod aq;
    pub mod aq_const;
    pub mod result;
}

pub mod util {
    pub mod dyn_query;
    pub mod file_util;
    pub mod id_util;
}

pub mod service {
    pub mod agg {
        pub mod role_agg_service;
        pub mod user_agg_service;
    }
    pub mod base {
        pub mod bill_form_service;
        pub mod button_action_service;
        pub mod common_attribute_service;
        pub mod component_entity_associate_service;
        pub mod component_entity_service;
        pub mod component_enum_service;
        pub mod component_module_service;
        pub mod component_node_ui_service;
        pub mod component_service;
        pub mod computation_attribute_service;
        pub mod data_type_service;
        pub mod dd_entity_service;
        pub mod dd_enum_service;
        pub mod dto_computation_attribute_service;
        pub mod dto_entity_associate_service;
        pub mod dto_entity_attribute_service;
        pub mod dto_entity_collection_service;
        pub mod dto_entity_service;
        pub mod dto_enum_associate_service;
        pub mod dto_enum_attribute_service;
        pub mod dto_enum_service;
        pub mod dto_module_service;
        pub mod dto_node_ui_service;
        pub mod entity_associate_service;
        pub mod entity_attribute_service;
        pub mod entity_collection_service;
        pub mod enum_associate_service;
        pub mod enum_attribute_service;
        pub mod ext_attribute_service;
        pub mod factory_service;
        pub mod menu_service;
        pub mod node_ui_service;
        pub mod project_service;
        pub mod query_service;
        pub mod role_menu_service;
        pub mod role_service;
        pub mod sub_project_service;
        pub mod tree_service;
        pub mod user_role_service;
        pub mod user_service;
    }
    pub mod ext {
        pub mod component {
            pub mod description_util;
        }
        pub mod component_ext_service;
        pub mod data_type_ext_service;
        pub mod dto_entity_collection_ext_service;
        pub mod entity_collection_ext_service;
        pub mod generator {
            pub mod component_comp {
                pub mod combination_generator;
                pub mod param_build;
            }
            pub mod component_enum {
                pub mod enum_generator;
                pub mod param_build;
            }
            pub mod component_single {
                pub mod param_build;
                pub mod single_generator;
            }
            pub mod data_transfer_object {
                pub mod data_transfer_object_generator;
                pub mod param_build;
            }
            pub mod entity_coll {
                pub mod coll_cache;
                pub mod entity_coll_generator;
                pub mod param_build;
            }
            pub mod genrate_const;
            pub mod genrate_util;
            pub mod ui_factory {
                pub mod ui_code_generator;
            }
            pub mod write_dir;
        }
        pub mod template_file_ext_service;
    }
}

pub mod dto {
    pub mod po {
        pub mod agg {
            pub mod role_agg_po;
            pub mod user_agg_po;
        }
        pub mod base {
            pub mod bill_form_po;
            pub mod button_action_po;
            pub mod common_attribute_po;
            pub mod component_entity_associate_po;
            pub mod component_entity_po;
            pub mod component_enum_po;
            pub mod component_module_po;
            pub mod component_node_ui_po;
            pub mod component_po;
            pub mod computation_attribute_po;
            pub mod data_type_po;
            pub mod dd_entity_po;
            pub mod dd_enum_po;
            pub mod dto_computation_attribute_po;
            pub mod dto_entity_associate_po;
            pub mod dto_entity_attribute_po;
            pub mod dto_entity_collection_po;
            pub mod dto_entity_po;
            pub mod dto_enum_associate_po;
            pub mod dto_enum_attribute_po;
            pub mod dto_enum_po;
            pub mod dto_module_po;
            pub mod dto_node_ui_po;
            pub mod entity_associate_po;
            pub mod entity_attribute_po;
            pub mod entity_collection_po;
            pub mod enum_associate_po;
            pub mod enum_attribute_po;
            pub mod ext_attribute_po;
            pub mod factory_po;
            pub mod menu_po;
            pub mod node_ui_po;
            pub mod project_po;
            pub mod query_po;
            pub mod role_menu_po;
            pub mod role_po;
            pub mod sub_project_po;
            pub mod tree_po;
            pub mod user_po;
            pub mod user_role_po;
        }
        pub mod ext {
            pub mod component {
                pub mod collection;
            }
            pub mod dto_collection {
                pub mod collection;
            }
            pub mod entity_collection {
                pub mod collection_po;
                pub mod join_entity_po;
            }
            pub mod generate {
                pub mod collection;
                pub mod component_combination;
                pub mod component_enum;
                pub mod component_single;
                pub mod dto_collection;
                pub mod ui_code;
            }
        }
    }
    pub mod vo {
        pub mod agg {
            pub mod role_agg_vo;
            pub mod user_agg_vo;
        }
        pub mod base {
            pub mod bill_form_vo;
            pub mod button_action_vo;
            pub mod common_attribute_vo;
            pub mod component_entity_associate_vo;
            pub mod component_entity_vo;
            pub mod component_enum_vo;
            pub mod component_module_vo;
            pub mod component_node_ui_vo;
            pub mod component_vo;
            pub mod computation_attribute_vo;
            pub mod data_type_vo;
            pub mod dd_entity_vo;
            pub mod dd_enum_vo;
            pub mod dto_computation_attribute_vo;
            pub mod dto_entity_associate_vo;
            pub mod dto_entity_attribute_vo;
            pub mod dto_entity_collection_vo;
            pub mod dto_entity_vo;
            pub mod dto_enum_associate_vo;
            pub mod dto_enum_attribute_vo;
            pub mod dto_enum_vo;
            pub mod dto_module_vo;
            pub mod dto_node_ui_vo;
            pub mod entity_associate_vo;
            pub mod entity_attribute_vo;
            pub mod entity_collection_vo;
            pub mod enum_associate_vo;
            pub mod enum_attribute_vo;
            pub mod ext_attribute_vo;
            pub mod factory_vo;
            pub mod menu_vo;
            pub mod node_ui_vo;
            pub mod project_vo;
            pub mod query_vo;
            pub mod role_menu_vo;
            pub mod role_vo;
            pub mod sub_project_vo;
            pub mod tree_vo;
            pub mod user_role_vo;
            pub mod user_vo;
        }
        pub mod ext {
            pub mod component {
                pub mod collection;
                pub mod description_info;
            }
            pub mod component_entity {
                pub mod detail;
                pub mod simple;
            }
            pub mod component_enum {
                pub mod detail;
                pub mod simple;
            }
            pub mod dd_enum {
                pub mod detail;
                pub mod simple;
            }
            pub mod dto_collection {
                pub mod entity_collection;
            }
            pub mod dto_entity {
                pub mod detail;
                pub mod simple;
            }
            pub mod dto_enum {
                pub mod simple;
            }
            pub mod entity {
                pub mod detail;
                pub mod simple;
            }
            pub mod entity_collection {
                pub mod entity_collection_vo;
                pub mod simple_coll_vo;
            }
            pub mod generate {
                pub mod generate_result;
            }
            pub mod menu {
                pub mod menu_vo;
            }
            pub mod project {
                pub mod component;
                pub mod dto_collection;
                pub mod entity_collection;
            }
            pub mod template_file {
                pub mod template_file;
            }
        }
    }
}
