//! api api_register.rs file. Generated by build, change in build/templates/api_register.tera
use actix_web::web;

use crate::api::{
    agg::role_agg_api as RoleAggApi,
    agg::user_agg_api as UserAggApi,
    base::bill_form_api as BillFormApi,
    base::button_action_api as ButtonActionApi,
    base::common_attribute_api as CommonAttributeApi,
    base::component_api as ComponentApi,
    base::component_entity_api as ComponentEntityApi,
    base::component_entity_associate_api as ComponentEntityAssociateApi,
    base::component_enum_api as ComponentEnumApi,
    base::component_module_api as ComponentModuleApi,
    base::component_node_ui_api as ComponentNodeUiApi,
    base::computation_attribute_api as ComputationAttributeApi,
    base::data_type_api as DataTypeApi,
    base::dd_entity_api as DdEntityApi,
    base::dd_enum_api as DdEnumApi,
    base::dto_computation_attribute_api as DtoComputationAttributeApi,
    base::dto_entity_api as DtoEntityApi,
    base::dto_entity_associate_api as DtoEntityAssociateApi,
    base::dto_entity_attribute_api as DtoEntityAttributeApi,
    base::dto_entity_collection_api as DtoEntityCollectionApi,
    base::dto_enum_api as DtoEnumApi,
    base::dto_enum_associate_api as DtoEnumAssociateApi,
    base::dto_enum_attribute_api as DtoEnumAttributeApi,
    base::dto_module_api as DtoModuleApi,
    base::dto_node_ui_api as DtoNodeUiApi,
    base::entity_associate_api as EntityAssociateApi,
    base::entity_attribute_api as EntityAttributeApi,
    base::entity_collection_api as EntityCollectionApi,
    base::enum_associate_api as EnumAssociateApi,
    base::enum_attribute_api as EnumAttributeApi,
    base::ext_attribute_api as ExtAttributeApi,
    base::factory_api as FactoryApi,
    base::menu_api as MenuApi,
    base::node_ui_api as NodeUiApi,
    base::project_api as ProjectApi,
    base::query_api as QueryApi,
    base::role_api as RoleApi,
    base::role_menu_api as RoleMenuApi,
    base::sub_project_api as SubProjectApi,
    base::tree_api as TreeApi,
    base::user_api as UserApi,
    base::user_role_api as UserRoleApi,
    common::param as Param,
    ext::component_entity_ext_api as ComponentEntityExtApi,
    ext::component_enum_ext_api as ComponentEnumExtApi,
    ext::component_ext_api as ComponentExtApi,
    ext::dd_entity_ext_api as DdEntityExtApi,
    ext::dd_enum_ext_api as DdEnumExtApi,
    ext::dto_entity_collection_ext_api as DtoEntityCollectionExtApi,
    ext::dto_entity_ext_api as DtoEntityExtApi,
    ext::dto_enum_ext_api as DtoEnumExtApi,
    ext::entity_collection_ext_api as EntityCollectionExtApi,
    ext::generator_api as GeneratorApi,
    ext::menu_ext_api as MenuExtApi,
    ext::project_ext_api as ProjectExtApi,
};

pub(crate) fn go_register(cfg: &mut web::ServiceConfig) {
    cfg.service(RoleAggApi::save);
    cfg.service(RoleAggApi::get_by_id);
    cfg.service(RoleAggApi::get_by_ids);
    cfg.service(RoleAggApi::aq_page);
    cfg.service(UserAggApi::save);
    cfg.service(UserAggApi::get_by_id);
    cfg.service(UserAggApi::get_by_ids);
    cfg.service(UserAggApi::aq_page);
    cfg.service(BillFormApi::add);
    cfg.service(BillFormApi::update);
    cfg.service(BillFormApi::remove);
    cfg.service(BillFormApi::batch_remove);
    cfg.service(BillFormApi::get_by_id);
    cfg.service(BillFormApi::get_by_ids);
    cfg.service(BillFormApi::page);
    cfg.service(ButtonActionApi::add);
    cfg.service(ButtonActionApi::update);
    cfg.service(ButtonActionApi::remove);
    cfg.service(ButtonActionApi::batch_remove);
    cfg.service(ButtonActionApi::get_by_id);
    cfg.service(ButtonActionApi::get_by_ids);
    cfg.service(ButtonActionApi::page);
    cfg.service(CommonAttributeApi::add);
    cfg.service(CommonAttributeApi::update);
    cfg.service(CommonAttributeApi::remove);
    cfg.service(CommonAttributeApi::batch_remove);
    cfg.service(CommonAttributeApi::get_by_id);
    cfg.service(CommonAttributeApi::get_by_ids);
    cfg.service(CommonAttributeApi::page);
    cfg.service(ComponentApi::add);
    cfg.service(ComponentApi::update);
    cfg.service(ComponentApi::remove);
    cfg.service(ComponentApi::batch_remove);
    cfg.service(ComponentApi::get_by_id);
    cfg.service(ComponentApi::get_by_ids);
    cfg.service(ComponentApi::page);
    cfg.service(ComponentEntityApi::add);
    cfg.service(ComponentEntityApi::update);
    cfg.service(ComponentEntityApi::remove);
    cfg.service(ComponentEntityApi::batch_remove);
    cfg.service(ComponentEntityApi::get_by_id);
    cfg.service(ComponentEntityApi::get_by_ids);
    cfg.service(ComponentEntityApi::page);
    cfg.service(ComponentEntityAssociateApi::add);
    cfg.service(ComponentEntityAssociateApi::update);
    cfg.service(ComponentEntityAssociateApi::remove);
    cfg.service(ComponentEntityAssociateApi::batch_remove);
    cfg.service(ComponentEntityAssociateApi::get_by_id);
    cfg.service(ComponentEntityAssociateApi::get_by_ids);
    cfg.service(ComponentEntityAssociateApi::page);
    cfg.service(ComponentEnumApi::add);
    cfg.service(ComponentEnumApi::update);
    cfg.service(ComponentEnumApi::remove);
    cfg.service(ComponentEnumApi::batch_remove);
    cfg.service(ComponentEnumApi::get_by_id);
    cfg.service(ComponentEnumApi::get_by_ids);
    cfg.service(ComponentEnumApi::page);
    cfg.service(ComponentModuleApi::add);
    cfg.service(ComponentModuleApi::update);
    cfg.service(ComponentModuleApi::remove);
    cfg.service(ComponentModuleApi::batch_remove);
    cfg.service(ComponentModuleApi::get_by_id);
    cfg.service(ComponentModuleApi::get_by_ids);
    cfg.service(ComponentModuleApi::page);
    cfg.service(ComponentNodeUiApi::add);
    cfg.service(ComponentNodeUiApi::update);
    cfg.service(ComponentNodeUiApi::remove);
    cfg.service(ComponentNodeUiApi::batch_remove);
    cfg.service(ComponentNodeUiApi::get_by_id);
    cfg.service(ComponentNodeUiApi::get_by_ids);
    cfg.service(ComponentNodeUiApi::page);
    cfg.service(ComputationAttributeApi::add);
    cfg.service(ComputationAttributeApi::update);
    cfg.service(ComputationAttributeApi::remove);
    cfg.service(ComputationAttributeApi::batch_remove);
    cfg.service(ComputationAttributeApi::get_by_id);
    cfg.service(ComputationAttributeApi::get_by_ids);
    cfg.service(ComputationAttributeApi::page);
    cfg.service(DataTypeApi::add);
    cfg.service(DataTypeApi::update);
    cfg.service(DataTypeApi::remove);
    cfg.service(DataTypeApi::batch_remove);
    cfg.service(DataTypeApi::get_by_id);
    cfg.service(DataTypeApi::get_by_ids);
    cfg.service(DataTypeApi::page);
    cfg.service(DdEntityApi::add);
    cfg.service(DdEntityApi::update);
    cfg.service(DdEntityApi::remove);
    cfg.service(DdEntityApi::batch_remove);
    cfg.service(DdEntityApi::get_by_id);
    cfg.service(DdEntityApi::get_by_ids);
    cfg.service(DdEntityApi::page);
    cfg.service(DdEnumApi::add);
    cfg.service(DdEnumApi::update);
    cfg.service(DdEnumApi::remove);
    cfg.service(DdEnumApi::batch_remove);
    cfg.service(DdEnumApi::get_by_id);
    cfg.service(DdEnumApi::get_by_ids);
    cfg.service(DdEnumApi::page);
    cfg.service(DtoComputationAttributeApi::add);
    cfg.service(DtoComputationAttributeApi::update);
    cfg.service(DtoComputationAttributeApi::remove);
    cfg.service(DtoComputationAttributeApi::batch_remove);
    cfg.service(DtoComputationAttributeApi::get_by_id);
    cfg.service(DtoComputationAttributeApi::get_by_ids);
    cfg.service(DtoComputationAttributeApi::page);
    cfg.service(DtoEntityApi::add);
    cfg.service(DtoEntityApi::update);
    cfg.service(DtoEntityApi::remove);
    cfg.service(DtoEntityApi::batch_remove);
    cfg.service(DtoEntityApi::get_by_id);
    cfg.service(DtoEntityApi::get_by_ids);
    cfg.service(DtoEntityApi::page);
    cfg.service(DtoEntityAssociateApi::add);
    cfg.service(DtoEntityAssociateApi::update);
    cfg.service(DtoEntityAssociateApi::remove);
    cfg.service(DtoEntityAssociateApi::batch_remove);
    cfg.service(DtoEntityAssociateApi::get_by_id);
    cfg.service(DtoEntityAssociateApi::get_by_ids);
    cfg.service(DtoEntityAssociateApi::page);
    cfg.service(DtoEntityAttributeApi::add);
    cfg.service(DtoEntityAttributeApi::update);
    cfg.service(DtoEntityAttributeApi::remove);
    cfg.service(DtoEntityAttributeApi::batch_remove);
    cfg.service(DtoEntityAttributeApi::get_by_id);
    cfg.service(DtoEntityAttributeApi::get_by_ids);
    cfg.service(DtoEntityAttributeApi::page);
    cfg.service(DtoEntityCollectionApi::add);
    cfg.service(DtoEntityCollectionApi::update);
    cfg.service(DtoEntityCollectionApi::remove);
    cfg.service(DtoEntityCollectionApi::batch_remove);
    cfg.service(DtoEntityCollectionApi::get_by_id);
    cfg.service(DtoEntityCollectionApi::get_by_ids);
    cfg.service(DtoEntityCollectionApi::page);
    cfg.service(DtoEnumApi::add);
    cfg.service(DtoEnumApi::update);
    cfg.service(DtoEnumApi::remove);
    cfg.service(DtoEnumApi::batch_remove);
    cfg.service(DtoEnumApi::get_by_id);
    cfg.service(DtoEnumApi::get_by_ids);
    cfg.service(DtoEnumApi::page);
    cfg.service(DtoEnumAssociateApi::add);
    cfg.service(DtoEnumAssociateApi::update);
    cfg.service(DtoEnumAssociateApi::remove);
    cfg.service(DtoEnumAssociateApi::batch_remove);
    cfg.service(DtoEnumAssociateApi::get_by_id);
    cfg.service(DtoEnumAssociateApi::get_by_ids);
    cfg.service(DtoEnumAssociateApi::page);
    cfg.service(DtoEnumAttributeApi::add);
    cfg.service(DtoEnumAttributeApi::update);
    cfg.service(DtoEnumAttributeApi::remove);
    cfg.service(DtoEnumAttributeApi::batch_remove);
    cfg.service(DtoEnumAttributeApi::get_by_id);
    cfg.service(DtoEnumAttributeApi::get_by_ids);
    cfg.service(DtoEnumAttributeApi::page);
    cfg.service(DtoModuleApi::add);
    cfg.service(DtoModuleApi::update);
    cfg.service(DtoModuleApi::remove);
    cfg.service(DtoModuleApi::batch_remove);
    cfg.service(DtoModuleApi::get_by_id);
    cfg.service(DtoModuleApi::get_by_ids);
    cfg.service(DtoModuleApi::page);
    cfg.service(DtoNodeUiApi::add);
    cfg.service(DtoNodeUiApi::update);
    cfg.service(DtoNodeUiApi::remove);
    cfg.service(DtoNodeUiApi::batch_remove);
    cfg.service(DtoNodeUiApi::get_by_id);
    cfg.service(DtoNodeUiApi::get_by_ids);
    cfg.service(DtoNodeUiApi::page);
    cfg.service(EntityAssociateApi::add);
    cfg.service(EntityAssociateApi::update);
    cfg.service(EntityAssociateApi::remove);
    cfg.service(EntityAssociateApi::batch_remove);
    cfg.service(EntityAssociateApi::get_by_id);
    cfg.service(EntityAssociateApi::get_by_ids);
    cfg.service(EntityAssociateApi::page);
    cfg.service(EntityAttributeApi::add);
    cfg.service(EntityAttributeApi::update);
    cfg.service(EntityAttributeApi::remove);
    cfg.service(EntityAttributeApi::batch_remove);
    cfg.service(EntityAttributeApi::get_by_id);
    cfg.service(EntityAttributeApi::get_by_ids);
    cfg.service(EntityAttributeApi::page);
    cfg.service(EntityCollectionApi::add);
    cfg.service(EntityCollectionApi::update);
    cfg.service(EntityCollectionApi::remove);
    cfg.service(EntityCollectionApi::batch_remove);
    cfg.service(EntityCollectionApi::get_by_id);
    cfg.service(EntityCollectionApi::get_by_ids);
    cfg.service(EntityCollectionApi::page);
    cfg.service(EnumAssociateApi::add);
    cfg.service(EnumAssociateApi::update);
    cfg.service(EnumAssociateApi::remove);
    cfg.service(EnumAssociateApi::batch_remove);
    cfg.service(EnumAssociateApi::get_by_id);
    cfg.service(EnumAssociateApi::get_by_ids);
    cfg.service(EnumAssociateApi::page);
    cfg.service(EnumAttributeApi::add);
    cfg.service(EnumAttributeApi::update);
    cfg.service(EnumAttributeApi::remove);
    cfg.service(EnumAttributeApi::batch_remove);
    cfg.service(EnumAttributeApi::get_by_id);
    cfg.service(EnumAttributeApi::get_by_ids);
    cfg.service(EnumAttributeApi::page);
    cfg.service(ExtAttributeApi::add);
    cfg.service(ExtAttributeApi::update);
    cfg.service(ExtAttributeApi::remove);
    cfg.service(ExtAttributeApi::batch_remove);
    cfg.service(ExtAttributeApi::get_by_id);
    cfg.service(ExtAttributeApi::get_by_ids);
    cfg.service(ExtAttributeApi::page);
    cfg.service(FactoryApi::add);
    cfg.service(FactoryApi::update);
    cfg.service(FactoryApi::remove);
    cfg.service(FactoryApi::batch_remove);
    cfg.service(FactoryApi::get_by_id);
    cfg.service(FactoryApi::get_by_ids);
    cfg.service(FactoryApi::page);
    cfg.service(MenuApi::add);
    cfg.service(MenuApi::update);
    cfg.service(MenuApi::remove);
    cfg.service(MenuApi::batch_remove);
    cfg.service(MenuApi::get_by_id);
    cfg.service(MenuApi::get_by_ids);
    cfg.service(MenuApi::page);
    cfg.service(NodeUiApi::add);
    cfg.service(NodeUiApi::update);
    cfg.service(NodeUiApi::remove);
    cfg.service(NodeUiApi::batch_remove);
    cfg.service(NodeUiApi::get_by_id);
    cfg.service(NodeUiApi::get_by_ids);
    cfg.service(NodeUiApi::page);
    cfg.service(ProjectApi::add);
    cfg.service(ProjectApi::update);
    cfg.service(ProjectApi::remove);
    cfg.service(ProjectApi::batch_remove);
    cfg.service(ProjectApi::get_by_id);
    cfg.service(ProjectApi::get_by_ids);
    cfg.service(ProjectApi::page);
    cfg.service(QueryApi::add);
    cfg.service(QueryApi::update);
    cfg.service(QueryApi::remove);
    cfg.service(QueryApi::batch_remove);
    cfg.service(QueryApi::get_by_id);
    cfg.service(QueryApi::get_by_ids);
    cfg.service(QueryApi::page);
    cfg.service(RoleApi::add);
    cfg.service(RoleApi::update);
    cfg.service(RoleApi::remove);
    cfg.service(RoleApi::batch_remove);
    cfg.service(RoleApi::get_by_id);
    cfg.service(RoleApi::get_by_ids);
    cfg.service(RoleApi::page);
    cfg.service(RoleMenuApi::add);
    cfg.service(RoleMenuApi::update);
    cfg.service(RoleMenuApi::remove);
    cfg.service(RoleMenuApi::batch_remove);
    cfg.service(RoleMenuApi::get_by_id);
    cfg.service(RoleMenuApi::get_by_ids);
    cfg.service(RoleMenuApi::page);
    cfg.service(SubProjectApi::add);
    cfg.service(SubProjectApi::update);
    cfg.service(SubProjectApi::remove);
    cfg.service(SubProjectApi::batch_remove);
    cfg.service(SubProjectApi::get_by_id);
    cfg.service(SubProjectApi::get_by_ids);
    cfg.service(SubProjectApi::page);
    cfg.service(TreeApi::add);
    cfg.service(TreeApi::update);
    cfg.service(TreeApi::remove);
    cfg.service(TreeApi::batch_remove);
    cfg.service(TreeApi::get_by_id);
    cfg.service(TreeApi::get_by_ids);
    cfg.service(TreeApi::page);
    cfg.service(UserApi::add);
    cfg.service(UserApi::update);
    cfg.service(UserApi::remove);
    cfg.service(UserApi::batch_remove);
    cfg.service(UserApi::get_by_id);
    cfg.service(UserApi::get_by_ids);
    cfg.service(UserApi::page);
    cfg.service(UserRoleApi::add);
    cfg.service(UserRoleApi::update);
    cfg.service(UserRoleApi::remove);
    cfg.service(UserRoleApi::batch_remove);
    cfg.service(UserRoleApi::get_by_id);
    cfg.service(UserRoleApi::get_by_ids);
    cfg.service(UserRoleApi::page);
    cfg.service(ComponentEntityExtApi::simple_aq);
    cfg.service(ComponentEntityExtApi::get_detail);
    cfg.service(ComponentEntityExtApi::simple_aq_page);
    cfg.service(ComponentEntityExtApi::get_description_data);
    cfg.service(ComponentEnumExtApi::simple_aq);
    cfg.service(ComponentEnumExtApi::get_detail);
    cfg.service(ComponentEnumExtApi::simple_aq_page);
    cfg.service(ComponentExtApi::ext_get_by_id);
    cfg.service(ComponentExtApi::save_by_action);
    cfg.service(ComponentExtApi::get_description_data);
    cfg.service(ComponentExtApi::remove_on_error_tip);
    cfg.service(DdEntityExtApi::get_detail_by_entity_id);
    cfg.service(DdEntityExtApi::get_detail_by_entity_ids);
    cfg.service(DdEntityExtApi::aq_detail);
    cfg.service(DdEnumExtApi::get_detail_by_enum_ids);
    cfg.service(DdEnumExtApi::aq_detail);
    cfg.service(DdEnumExtApi::ed);
    cfg.service(DtoEntityCollectionExtApi::ext_get_by_id);
    cfg.service(DtoEntityCollectionExtApi::get_full_coll);
    cfg.service(DtoEntityCollectionExtApi::save_by_action);
    cfg.service(DtoEntityCollectionExtApi::copy_by_id);
    cfg.service(DtoEntityExtApi::get_dto_attr_by_ids);
    cfg.service(DtoEntityExtApi::aq_detail);
    cfg.service(DtoEnumExtApi::aq_detail);
    cfg.service(EntityCollectionExtApi::ext_get_by_id);
    cfg.service(EntityCollectionExtApi::get_full_coll);
    cfg.service(EntityCollectionExtApi::get_simple_collection);
    cfg.service(EntityCollectionExtApi::save_by_action);
    cfg.service(EntityCollectionExtApi::copy_by_id);
    cfg.service(GeneratorApi::generate_single_file);
    cfg.service(GeneratorApi::entity_coll_generate_full);
    cfg.service(GeneratorApi::entity_coll_generate_part);
    cfg.service(GeneratorApi::factory_generate);
    cfg.service(GeneratorApi::generate_enum_part);
    cfg.service(GeneratorApi::generate_enum_full);
    cfg.service(GeneratorApi::generate_combination);
    cfg.service(GeneratorApi::generate_single);
    cfg.service(GeneratorApi::generate_input_full);
    cfg.service(GeneratorApi::generate_input_part);
    cfg.service(GeneratorApi::generate_output_full);
    cfg.service(GeneratorApi::generate_output_part);
    cfg.service(MenuExtApi::ext_get_by_id);
    cfg.service(ProjectExtApi::aq_detail);
    cfg.service(ProjectExtApi::sub_project_aq);
    cfg.service(ProjectExtApi::entity_collection_aq);
    cfg.service(ProjectExtApi::component_aq);
    cfg.service(ProjectExtApi::dto_collection_aq);

}