//! api lib.rs file. Generated by build, change in build/templates/api_lib.tera

mod app;

pub fn main() {
    let result = app::start();

    if let Some(err) = result.err() {
        println!("Error: {err}");
    }
}

mod conf {
    pub(crate) mod error_handle;
    pub(crate) mod response_handle;
}

mod api_register;

mod api {
        pub mod agg {
            pub mod role_agg_api;
            pub mod user_agg_api;
        }
        pub mod base {
            pub mod bill_form_api;
            pub mod button_action_api;
            pub mod common_attribute_api;
            pub mod component_api;
            pub mod component_entity_api;
            pub mod component_entity_associate_api;
            pub mod component_enum_api;
            pub mod component_module_api;
            pub mod component_node_ui_api;
            pub mod computation_attribute_api;
            pub mod data_type_api;
            pub mod dd_entity_api;
            pub mod dd_enum_api;
            pub mod dto_computation_attribute_api;
            pub mod dto_entity_api;
            pub mod dto_entity_associate_api;
            pub mod dto_entity_attribute_api;
            pub mod dto_entity_collection_api;
            pub mod dto_enum_api;
            pub mod dto_enum_associate_api;
            pub mod dto_enum_attribute_api;
            pub mod dto_module_api;
            pub mod dto_node_ui_api;
            pub mod entity_associate_api;
            pub mod entity_attribute_api;
            pub mod entity_collection_api;
            pub mod enum_associate_api;
            pub mod enum_attribute_api;
            pub mod ext_attribute_api;
            pub mod factory_api;
            pub mod menu_api;
            pub mod node_ui_api;
            pub mod project_api;
            pub mod query_api;
            pub mod role_api;
            pub mod role_menu_api;
            pub mod sub_project_api;
            pub mod tree_api;
            pub mod user_api;
            pub mod user_role_api;
        }
        pub mod common {
            pub mod param;
        }
        pub mod ext {
            pub mod component_entity_ext_api;
            pub mod component_enum_ext_api;
            pub mod component_ext_api;
            pub mod dd_entity_ext_api;
            pub mod dd_enum_ext_api;
            pub mod dto_entity_collection_ext_api;
            pub mod dto_entity_ext_api;
            pub mod dto_enum_ext_api;
            pub mod entity_collection_ext_api;
            pub mod generator_api;
            pub mod menu_ext_api;
            pub mod project_ext_api;
            pub mod template_file_api;
        }
}

