//! entity lib.rs file. Generated by build, if necessary please change in build/templates/entity_lib.tera
pub mod common {
    pub mod desc;
}

pub mod conf {
    pub mod meta_init;
}

pub mod entity {
    pub mod bill_form;
    pub mod button_action;
    pub mod common_attribute;
    pub mod component;
    pub mod component_entity;
    pub mod component_entity_associate;
    pub mod component_enum;
    pub mod component_module;
    pub mod component_node_ui;
    pub mod computation_attribute;
    pub mod data_type;
    pub mod dd_entity;
    pub mod dd_enum;
    pub mod dto_computation_attribute;
    pub mod dto_entity;
    pub mod dto_entity_associate;
    pub mod dto_entity_attribute;
    pub mod dto_entity_collection;
    pub mod dto_enum;
    pub mod dto_enum_associate;
    pub mod dto_enum_attribute;
    pub mod dto_module;
    pub mod dto_node_ui;
    pub mod entity_associate;
    pub mod entity_attribute;
    pub mod entity_collection;
    pub mod enum_associate;
    pub mod enum_attribute;
    pub mod ext_attribute;
    pub mod factory;
    pub mod menu;
    pub mod node_ui;
    pub mod project;
    pub mod query;
    pub mod role;
    pub mod role_menu;
    pub mod sub_project;
    pub mod token;
    pub mod tree;
    pub mod user;
    pub mod user_role;
}

pub mod meta {
    pub mod bill_form_desc;
    pub mod button_action_desc;
    pub mod common_attribute_desc;
    pub mod component_desc;
    pub mod component_entity_associate_desc;
    pub mod component_entity_desc;
    pub mod component_enum_desc;
    pub mod component_module_desc;
    pub mod component_node_ui_desc;
    pub mod computation_attribute_desc;
    pub mod data_type_desc;
    pub mod dd_entity_desc;
    pub mod dd_enum_desc;
    pub mod dto_computation_attribute_desc;
    pub mod dto_entity_associate_desc;
    pub mod dto_entity_attribute_desc;
    pub mod dto_entity_collection_desc;
    pub mod dto_entity_desc;
    pub mod dto_enum_associate_desc;
    pub mod dto_enum_attribute_desc;
    pub mod dto_enum_desc;
    pub mod dto_module_desc;
    pub mod dto_node_ui_desc;
    pub mod entity_associate_desc;
    pub mod entity_attribute_desc;
    pub mod entity_collection_desc;
    pub mod enum_associate_desc;
    pub mod enum_attribute_desc;
    pub mod ext_attribute_desc;
    pub mod factory_desc;
    pub mod menu_desc;
    pub mod node_ui_desc;
    pub mod project_desc;
    pub mod query_desc;
    pub mod role_desc;
    pub mod role_menu_desc;
    pub mod sub_project_desc;
    pub mod token_desc;
    pub mod tree_desc;
    pub mod user_desc;
    pub mod user_role_desc;
}
